fix - 2

diff --git a/.github/workflows/macos-build.yml b/.github/workflows/macos-build.yml
--- a/.github/workflows/macos-build.yml
+++ b/.github/workflows/macos-build.yml
@@ -13,6 +13,8 @@ jobs:
     runs-on: macos-latest
 
     steps:
+      - name: Set BASE_DIR
+        run: echo "BASE_DIR=$(pwd)" >> $GITHUB_ENV
       # Step 1: Check out the repository
       - uses: actions/checkout@v4
       # Step 2: Set up Python
@@ -99,12 +101,12 @@ jobs:
       - name: Build executable
         run: |
           pyinstaller --onefile --windowed \
-            --add-data "$BASE_DIR/images:images" \
-            --add-data "$BASE_DIR/build_assets/en-model.slp:pattern/text/en" \
-            --add-data "$BASE_DIR/CTkXYFrame:CTkXYFrame" \
-            --add-binary "/opt/homebrew/opt/portaudio/lib/libportaudio.2.dylib:." \
-            --add-binary "/opt/homebrew/bin/ffmpeg:." \
-            --add-binary "/opt/homebrew/bin/ffprobe:." \
+            --add-data "$(pwd)/images:images" \
+            --add-data "$(pwd)/build_assets/en-model.slp:pattern/text/en" \
+            --add-data "$(pwd)/CTkXYFrame:CTkXYFrame" \
+            --add-binary "$PORTAUDIO_PATH:." \
+            --add-binary "$FFMPEG_PATH:." \
+            --add-binary "$FFPROBE_PATH:." \
             --add-data "$VIRTUAL_ENV/lib/python3.11/site-packages/lightning_fabric:lightning_fabric" \
             --add-data "$VIRTUAL_ENV/lib/python3.11/site-packages/whisper:whisper" \
             --add-data "$VIRTUAL_ENV/lib/python3.11/site-packages/filelock:filelock" \
@@ -115,7 +117,26 @@ jobs:
             --hidden-import "torchvision" \
             --hidden-import "pytorch_lightning" \
             --hidden-import "pyannote.audio" \
-            GUI.py
+            "$(pwd)/GUI.py"
+      #######################################      
+      - name: Debug Directory Structure
+        run: |
+          echo "Current Directory: $(pwd)"
+          echo "Listing Files and Directories:"
+          ls -R
+
+      - name: Verify Required Files and Directories
+        run: |
+          if [ ! -d "$BASE_DIR/images" ]; then
+            echo "Error: Directory $BASE_DIR/images not found!"
+            exit 1
+          fi
+          if [ ! -d "$BASE_DIR/build_assets" ]; then
+            echo "Error: Directory $BASE_DIR/build_assets not found!"
+            exit 1
+          fi      
+      #######################################      
+
       # Step 9: Run the Saltify build script
       - name: Run Saltify Build Script
         run: |
